### ISSUE TITLE
Build ASP.NET MCV project must be Nuget restore

### ISSUE THREAD

**Issue by l7960261** [CodingWorkshop/Bumblebee#3]
Build error because not add the nuget restore task before build task.

Please fix the bug, thank you.

![image](https://cloud.githubusercontent.com/assets/4183364/25747728/13106b12-31db-11e7-91e5-5cf0457eeaa2.png)

**Comment by cyan92128505** [comment]
We use electron-edge and store dependent file which used in temp folder, then the issue were resolved.
