### ISSUE TITLE
Apply NetNative to Msbuild module, please.

### ISSUE THREAD

**Issue by cyan92128505** [CodingWorkshop/Bumblebee#5]
We should need to fix module which combine other modules, can be reinstall nugit package and git initial.

**Comment by l7960261** [comment]
@cyan92128505 Combine netnative into msbuild module at [7251c6e](https://github.com/CodingWorkshop/Bumblebee/commit/7521c6e38eaf26d57814fec0d263fcfaed8dcee5)
