### ISSUE TITLE
Store configuration information

### ISSUE THREAD

**Issue by cyan92128505** [CodingWorkshop/Bumblebee#7]
When user added a path and action over, user need to add path again.
In the scene, it's too more step.

**Comment by l7960261** [comment]
We store as json file, and create a 'user-config.service' to control save or nonsave user settings.
[ea6e9ca](https://github.com/CodingWorkshop/Bumblebee/commit/ea6e9ca7f51188a0ec04d1fb7d9a1d05fceb0cf6)
